python-version = "3.10.0"
python-interpreter-path = "C:\\Users\\rravi\\AppData\\Local\\Programs\\Python\\Python310\\python.exe"
search-path = [
  "app/backend"
]
project-excludes = [
  "notebooks/**",
  "**/node_modules/**"
]
